#Build settings

theme: minima

#To use any other Jekyll theme hosted on GitHub, type remote_theme: THEME-NAME, replacing THEME-NAME with the name of the theme as shown in the README of the theme's repository.
#remote-theme: benbalter/retlab
